import{S as p,i as g}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const f="/goit-js-hw-11/assets/alert-7962080a.svg",d="https://pixabay.com/api/",c={key:"40878457-91c7c8077e8a58c5727309d44",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:18},y=document.querySelector(".form"),m=document.querySelector(".searchTerm"),h=document.querySelector(".search-btn"),w=document.querySelector(".loader"),u=document.querySelector(".gallery"),L=new p(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250});y.addEventListener("submit",s=>{if(s.preventDefault(),m.value.trim().length<3){l("Please, enter search term!");return}v().then(t=>S(t)).catch(t=>l(t.toString()))});function v(){u.innerHTML="",o(!0),c.q=m.value.trim();const s=new URLSearchParams(c);return fetch(`${d}?${s}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function S(s){if(s.total===0){l("Sorry, there are no images matching your search query. Please try again!"),o(!1);return}const t=s.hits.map(r=>`<a class="gallery-link" href="${r.largeImageURL}"><span class="gallery-item"><img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" /></span>
            <span class="img-stat">
            <span class="img-stat-item"><span class="img-stat-title">Likes</span><span class="img-stat-val">${r.likes}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Views</span><span class="img-stat-val">${r.views}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Comments</span><span class="img-stat-val">${r.comments}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Downloads</span><span class="img-stat-val">${r.downloads}</span></span>
            </span>
            </a>`).join("");o(!1),u.insertAdjacentHTML("beforeend",t),L.refresh()}function o(s=!0){w.style.display=s?"inline-block":"none",h.disabled=s}function l(s){g.show({position:"topCenter",iconUrl:f,messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,message:s})}
//# sourceMappingURL=commonHelpers.js.map
